---
driver:
  name: vagrant
  synced_folders:
    - ["../rails-app", "/home/vagrant/microwave-workspace"]
  network:
    - ["forwarded_port", {guest: 3000, host: 5000}]

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
    driver:
      box: microwave/trusty64

suites:
  - name: microwave-rails-chef
    run_list: 
      - microwave-rails-chef
